# Generated by Django 5.0.2 on 2024-02-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_movie_movie_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_cover_image',
            field=models.ImageField(upload_to='movies/'),
        ),
    ]
