# Generated by Django 5.0.2 on 2024-02-27 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_movie_movie_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_created_at', models.DateTimeField(auto_now_add=True)),
                ('review_updated_at', models.DateTimeField(auto_now=True)),
                ('movie_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('movie_review_text', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.movie')),
            ],
        ),
    ]
