# Generated by Django 5.0.2 on 2024-02-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_updated_at', models.DateTimeField(auto_now=True)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_year', models.IntegerField()),
                ('movie_director', models.CharField(max_length=100)),
                ('movie_cover_image', models.ImageField(upload_to='personal_blog\\reviews\\static\\movies\\<django.db.models.fields.CharField>\\')),
                ('movie_rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
